-- DELIVERY DATABASE SCHEMA

CREATE TABLE IF NOT EXISTS delivery_partners (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL UNIQUE,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  profile_photo_url TEXT,
  vehicle_type VARCHAR(50),
  vehicle_registration VARCHAR(100),
  vehicle_photo_url TEXT,
  license_number VARCHAR(100),
  license_photo_url TEXT,
  national_id VARCHAR(100),
  national_id_photo_url TEXT,
  status VARCHAR(50) DEFAULT 'pending',
  online_status VARCHAR(50) DEFAULT 'offline',
  current_status VARCHAR(50) DEFAULT 'break',
  approval_status VARCHAR(50) DEFAULT 'pending',
  approved_at TIMESTAMP,
  approved_by VARCHAR(255),
  total_deliveries INTEGER DEFAULT 0,
  successful_deliveries INTEGER DEFAULT 0,
  failed_deliveries INTEGER DEFAULT 0,
  average_rating DECIMAL(3, 2) DEFAULT 0,
  total_ratings INTEGER DEFAULT 0,
  current_earnings_today DECIMAL(10, 2) DEFAULT 0,
  current_earnings_week DECIMAL(10, 2) DEFAULT 0,
  current_earnings_month DECIMAL(10, 2) DEFAULT 0,
  lifetime_earnings DECIMAL(15, 2) DEFAULT 0,
  performance_score DECIMAL(3, 2) DEFAULT 0,
  last_login TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_email (email),
  INDEX idx_phone (phone),
  INDEX idx_status (status),
  INDEX idx_online_status (online_status)
);

CREATE TABLE IF NOT EXISTS deliveries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id VARCHAR(255) NOT NULL,
  delivery_partner_id UUID REFERENCES delivery_partners(id),
  pickup_location_lat DECIMAL(10, 8),
  pickup_location_lng DECIMAL(11, 8),
  delivery_location_lat DECIMAL(10, 8),
  delivery_location_lng DECIMAL(11, 8),
  estimated_distance DECIMAL(10, 2),
  estimated_time INTEGER,
  actual_distance DECIMAL(10, 2),
  actual_time INTEGER,
  base_fare DECIMAL(10, 2),
  distance_fare DECIMAL(10, 2),
  tip_amount DECIMAL(10, 2) DEFAULT 0,
  bonus_amount DECIMAL(10, 2) DEFAULT 0,
  total_amount DECIMAL(10, 2),
  payment_status VARCHAR(50),
  delivery_status VARCHAR(50),
  proof_photo_url TEXT,
  otp_verified BOOLEAN DEFAULT FALSE,
  cod_amount DECIMAL(10, 2),
  cod_collected DECIMAL(10, 2),
  cod_payment_status VARCHAR(50),
  started_at TIMESTAMP,
  completed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_order_id (order_id),
  INDEX idx_delivery_partner_id (delivery_partner_id),
  INDEX idx_delivery_status (delivery_status)
);

CREATE TABLE IF NOT EXISTS delivery_earnings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  delivery_partner_id UUID NOT NULL REFERENCES delivery_partners(id),
  delivery_id UUID REFERENCES deliveries(id),
  earnings_type VARCHAR(50),
  amount DECIMAL(10, 2),
  earneed_date DATE,
  payment_status VARCHAR(50),
  paid_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_delivery_partner_id (delivery_partner_id),
  INDEX idx_earned_date (earneed_date)
);

CREATE TABLE IF NOT EXISTS delivery_performance_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  delivery_partner_id UUID NOT NULL REFERENCES delivery_partners(id),
  delivery_id UUID REFERENCES deliveries(id),
  on_time_delivery BOOLEAN,
  rating INTEGER,
  review TEXT,
  completion_time INTEGER,
  distance_variance DECIMAL(10, 2),
  customer_feedback TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_delivery_partner_id (delivery_partner_id)
);

CREATE TABLE IF NOT EXISTS delivery_zones (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  zone_name VARCHAR(100),
  zone_polygon GEOMETRY,
  base_fare DECIMAL(10, 2),
  per_km_fare DECIMAL(10, 2),
  min_fare DECIMAL(10, 2),
  max_fare DECIMAL(10, 2),
  delivery_time_minutes INTEGER,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_zone_name (zone_name)
);
